# Generated by Django 3.0.7 on 2023-03-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(max_length=10)),
                ('max_locatarios', models.IntegerField(default=4)),
                ('descricao', models.CharField(default='Biopark Apartamentos', max_length=100)),
                ('bloco', models.CharField(choices=[('A', 'Aurora'), ('B', 'Brasil'), ('C', 'Coutry')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('Q', 'Quarto'), ('A', 'Apartamento')], default='A', max_length=1)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Apartamento', verbose_name='Apartamento')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Locatario', verbose_name='Locatario')),
            ],
        ),
    ]
