# Generated by Django 4.1.7 on 2023-03-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(max_length=10)),
                ('numero_quartos', models.IntegerField(default=4, max_length=4)),
                ('max_locatarios', models.IntegerField(default=1)),
                ('descricao', models.CharField(default='Biopark Apartamentos', max_length=100)),
                ('bloco', models.CharField(choices=[('A', 'Aurora'), ('B', 'Brasil'), ('C', 'Coutry')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('numero_apartamento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('modelo', models.CharField(choices=[('A', 'Apartamento')], default='A', max_length=1)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.apartamento', verbose_name='Apartamento')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.locatario', verbose_name='Locatario')),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='edificios.edificio'),
        ),
    ]
