# Generated by Django 3.0.7 on 2023-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_apartamento', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('bloco', models.CharField(choices=[('A', 'Aurora'), ('B', 'Brasil'), ('C', 'Coutry')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Locatarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
