# Generated by Django 4.1.7 on 2023-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='numero_apartamento',
            field=models.IntegerField(max_length=10),
        ),
    ]
