# Generated by Django 3.0.7 on 2023-03-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locatarios',
            new_name='Locatario',
        ),
    ]
