# Generated by Django 3.0.7 on 2023-03-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0003_auto_20230305_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('Q', 'Quarto'), ('A', 'Apartamento')], default='A', max_length=1)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Apartamento', verbose_name='Apartamento')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Locatario', verbose_name='Locatario')),
            ],
        ),
    ]
