# Generated by Django 3.0.7 on 2023-03-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0004_locado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locatario',
            name='data_nascimento',
        ),
    ]
